### ISSUE TITLE
Write instructions on how to run the project for development

### ISSUE THREAD

**Issue by sahibjotsaggu** [yogaboll/react-kanban#1]
I am trying to run the project for development and using the `npm run build` command (after running mongo) gives the following error:

```
/Users/sahibjot/Document/Github/react-kanban/node_modules/webpack/lib/TemplatedPathPlugin.js:43
       throw new Error(
       ^
Error: Path variable [contenthash:6] not implemented in this context: bundle.[contenthash:6].css
     at fn(../node_modules/webpack/lib/TemplatedPathPlugin.js:43:11)
     at fn(../node_modules/webpack/lib/TemplatedPathPlugin.js:31:16)
     at RegExp.[Symbol.replace] (native)
     String.replace (native)
...
```

Also, not able to select the error logs.

Node: v7.10.0
macOS High Sierra: Version 10.13.3
Mongo: Version 3.0.5

**Comment by liuyidi** [comment]
I met the same problem

**Comment by SkyzohKey** [comment]
I guess you should replace `contenthash` by `hash` in the webpack configs. Then re-run `npm run build`.

**Comment by sahibjotsaggu** [comment]
@SkyzohKey That seems to compile. 

I can't tell what port the server is running on.

```
→ npm run serve

> react-kanban@0.1.0 serve /Users/sahibjot/Documents/Github/react-kanban
> nodemon dist/server.js

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
```

**Comment by SkyzohKey** [comment]
Default port when it comes to react: 3000. Those are only suppositions xD

**Comment by SkyzohKey** [comment]
OK checked the server code and it should runs on http://127.0.0.1:1337. You can pass your own port as a PORT env variable.

**Comment by sahibjotsaggu** [comment]
But that's the server, what about the client?

**Comment by SkyzohKey** [comment]
The server does serves the client, nope? I think that's to ensure SSR is properly working while developing in dev' mode.

Actually  i've nerver ran this app. I just looked at the issue tracker and bemieved my ''experience'' could help a bit. 😇

For more specific questions please mention the respository owner. 🤘

**Comment by mjuraj** [comment]
I built the code and ran it with `npm build serve`, but http://127.0.0.1:1337 didn't serve anything.

**Comment by SkyzohKey** [comment]
Ok I've investigated a bit and here is the installation process (for developing, you'll have to figure how to put that in prod' yourself):
1. Clone the repository & install dependencies:
	```bash
	$ git clone https://github.com/yogaboll/react-kanban.git
	$ cd react-kanban/
	$ yarn # or `npm install`
	```
2. Fix webpack config:
	```bash
	$ sed -i 's/contenthash:6/hash:6/' webpack.config.client.js
	```
3. Build the project:
	```bash
	$ yarn build # or `npm run build`
	```
4. Start the MongoDB service (on Arch-like):
	```bash
	$ sudo systemctl start mongodb`
	```
5. Set the MongoDB env vars:
	```bash
	$ export MONGODB_URL=mongodb://127.0.0.1:27017
	$ export MONGODB_NAME="react-kanban"
	$ export SESSION_SECRET="some_random_private_key"
	```
6. Set the Passport env vars:
	```bash
	$ export TWITTER_API_KEY="YOUR_TWITTER_API_KEY"
	$ export TWITTER_API_SECRET="YOUR_TWITTER_API_SECRET"
	$ export GOOGLE_CLIENT_ID="YOUR_GOOGLE_CLIENT_ID"
	$ export GOOGLE_CLIENT_SECRET="YOUR_GOOGLE_CLIENT_SECRET"
	$ export ROOT_URL="http://127.0.0.1:1337" # This is the root url where the app lives.
	```
7. Serve the project:
	```bash
	$ yarn serve # or `npm run serve`
	```
8. **Open the webapp at http://127.0.0.1:1337**

@yogaboll Feel free to correct this answer or to use it in your readme ;)

**Comment by daeschwed** [comment]
@SkyzohKey brilliant, thanks so much for sharing.

Docker anyone? Simply replace step 4 with

```bash
$ docker pull mongo
$ docker run --name mongodb -d -p 27017:27017 mongo
```

In case you don't require the OAuth stuff and just want to have a look, it's as simple as commenting out
```js
src/server/server.js:28
```
```js
// configurePassport(db);
```

Maybe @SkyzohKey can chip in with some `sed`magic for that part, too?

@yogaboll mycket bra, tack! 💯 poäng

**Comment by SkyzohKey** [comment]
@daeschwed Here's the sed magic you asked for:

To remove passport auth, just run the following. :yum: 
```bash
$ sed -e '/configurePassport/ s/^#*/  \/\//' -i test.js
```

**Comment by yogaboll** [comment]
Hey, sorry for not responding earlier.
@SkyzohKey Good job on reverse engineering the setup.

I added a development section to the README which describes how to set up the project.

I also created a branch called simple-dev, where I've removed all the database and auth related code. By cloning this branch, you don't have to set up a .env file, a local mongodb instance and social sign-in credentials (a lot of work). So hopefully now it should be pretty easy for folks who want to set up the project locally.

I'm curious as to why you guys need to replace "contenthash" with "hash" in the webpack config. It works on my machine obviously. I don't get why it wouldn't work for everyone. Should I change it?

**Comment by SkyzohKey** [comment]
Nice to hear! About the content hash. Webpack dérivés ''contenthash'' by hashing the content of the file, while it Just generate a random hash with ''hash''. Which avoid caching strangenesses. Also, it doesn't work on other machines because of how webpack does perform the hash of the file on these platforms I guess. So yeah ''hash'' is saner. :)

**Comment by yogaboll** [comment]
Ok, I changed it to hash.
