### ISSUE TITLE
Items move to the top

### ISSUE THREAD

**Issue by pupeno** [yogaboll/react-kanban#11]
In the demo here:

https://brockreece.github.io/vue-kanban/

if I take item with id 4 and try to put it under id 6, in flashes as it's going there, but then jumps to the top of the approved column. Is this a bug? a misconfiguration? something else?

If necessary, I can record a video of this.

**Comment by markusenglund** [comment]
Vue-kanban has nothing to do with this project 😄 You should probably ask the guy that actually built it.

**Comment by pupeno** [comment]
Oops. Sorry. I was looking at the two projects and ended up submitting a
bug for the wrong one. My apologies.

**Comment by markusenglund** [comment]
No worries mate
