### ISSUE TITLE
How do you make the `react-beautiful-dnd` auto scroll horizontally ？

### ISSUE THREAD

**Issue by zjh1943** [yogaboll/react-kanban#3]
Hi, I'm using `react-beautiful-dnd` to make our kanban function. But the problem about horizontally auto-scrolling trouble me very much. The issue is submit [here](https://github.com/atlassian/react-beautiful-dnd/issues/362). In short, (as the author said), the `react-beatiful-dnd` will not auto scroll if I have two level scrollable containers (one is horizontal, the other is vertical).
But when I read your code and play with your demo, there is not the problem like mine. So, what magic do you use to solve the problem? Could you tell me? Thx very much! @yogaboll

**Comment by zjh1943** [comment]
@yogaboll Thank you very much, for your detailed explanation. You did much help to me. 
You help me do decide to not use `react-beautiful-dnd` in my project.
I'm now using `react-dnd` and `react-virtulize` to implement my kanban. This example <https://github.com/zjh1943/react-virtual-kanban> help me a lot.

Thank you~

**Comment by yogaboll** [comment]
Ok, good luck!
